management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    openfeign:
      client:
        config:
          library:
            url: #define Library service base URL
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  application:
    name: library-warehouse
  jackson:
    serialization:
      indent_output: true
    deserialization:
      fail-on-unknown-properties: true
  jmx:
    enabled: false